# Generated by Django 5.0 on 2024-10-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="E-mail do usuário (será usado para login)",
                max_length=254,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="login",
            field=models.CharField(
                help_text="Login de acesso do usuário",
                max_length=50,
                verbose_name="Login",
            ),
        ),
    ]
