# Generated by Django 5.0 on 2024-10-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="document",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="CNPJ"
            ),
        ),
    ]
