# Generated by Django 5.1.6 on 2025-03-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='type',
            field=models.CharField(choices=[('VEI', 'Veículo'), ('ARM', 'Armamento'), ('MAT', 'Material'), ('UNI', 'Uniforme'), ('EQUIP', 'Equipamento'), ('SERV', 'Serviço')], default='MAT', max_length=5, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='unit_measure',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Kilograma'), ('ML', 'Mililitro'), ('DAY', 'Dia'), ('HR', 'Hora'), ('MON', 'Mês')], default='UN', max_length=5, verbose_name='Unidade de Medida'),
        ),
    ]
