# Generated by Django 5.1.6 on 2025-03-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_supply_type_alter_supply_unit_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='type',
            field=models.CharField(choices=[('VEI', 'Veículo'), ('ARM', 'Armamento'), ('MAT', 'Material'), ('UNI', 'Uniforme'), ('EQUIP', 'Equipamento'), ('SERV', 'Serviço'), ('MAO', 'Mão de Obra')], default='MAT', max_length=5, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='unit_measure',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Kilograma'), ('ML', 'Mililitro'), ('L', 'Litro'), ('M3', 'Metro Cubico'), ('M', 'Metro'), ('KM', 'Kilometros'), ('M2', 'Metro Quadrado'), ('DAY', 'Dia'), ('HR', 'Hora'), ('MON', 'Mês'), ('YEAR', 'Ano')], default='UN', max_length=5, verbose_name='Unidade de Medida'),
        ),
    ]
