# Generated by Django 5.1.6 on 2025-03-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_supply_type_alter_supply_unit_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('document', 'company'), name='unique_document_per_company'),
        ),
    ]
