# Generated by Django 5.1.2 on 2024-10-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_customer_options_alter_customer_customer_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contract",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="CustomerType",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
    ]
