# Generated by Django 5.1.6 on 2025-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customer_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='ean_code',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Código EAN'),
        ),
        migrations.AddConstraint(
            model_name='supply',
            constraint=models.UniqueConstraint(fields=('ean_code', 'company'), name='unique_ean_code_per_company'),
        ),
    ]
