# Generated by Django 5.1.6 on 2025-03-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_supply_ean_code_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.UniqueConstraint(fields=('acronym', 'company'), name='unique_acronym_per_company'),
        ),
    ]
