# Generated by Django 5.1.2 on 2024-10-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Descrição"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("tax", "Imposto"), ("fee", "Taxa")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("acronym", models.CharField(max_length=10, verbose_name="Sigla")),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("federal", "Federal"),
                            ("state", "Estadual"),
                            ("municipal", "Municipal"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "calc_operator",
                    models.CharField(
                        choices=[
                            ("%", "Percentual"),
                            ("0", "Fixo"),
                            ("+", "Adição"),
                            ("-", "Subtração"),
                            ("*", "Multiplicação"),
                            ("/", "Divisão"),
                        ],
                        default="%",
                        max_length=1,
                        verbose_name="Operador de Cálculo",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Valor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Imposto",
                "verbose_name_plural": "Impostos",
                "db_table": "tax",
            },
        ),
    ]
