# Generated by Django 5.1.2 on 2024-10-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_tax"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "nick_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Apelido"
                    ),
                ),
                (
                    "ean_code",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="Código EAN",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "unit_measure",
                    models.CharField(
                        choices=[
                            ("UN", "Unidade"),
                            ("KG", "Kilograma"),
                            ("ML", "Mililitro"),
                        ],
                        default="UN",
                        max_length=2,
                        verbose_name="Unidade de Medida",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VEI", "Veículo"),
                            ("ARM", "Armamento"),
                            ("MAT", "Material"),
                            ("UNI", "Uniforme"),
                        ],
                        default="MAT",
                        max_length=3,
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supply",
                "verbose_name_plural": "Supplies",
                "db_table": "supplies",
                "ordering": ["name"],
            },
        ),
    ]
